class ExperienceLevel:
    ENTRY_LEVEL = "ENTRY_LEVEL"
    MID_LEVEL = "MID_LEVEL"
    SENIOR_LEVEL = "SENIOR_LEVEL"

class EducationLevel:
    BACHELORS_DEGREE = "BACHELORS_DEGREE"
    MASTERS_DEGREE = "MASTERS_DEGREE"
    DOCTORAL_DEGREE = "DOCTORAL_DEGREE"

class JobType:
    FULLTIME = "FULLTIME"
    PARTTIME = "PARTTIME"
    CONTRACT = "CONTRACT"
    INTERNSHIP = "INTERNSHIP"
    TEMPORARY = "TEMPORARY"
    
EducationLevelMap ={
    'BACHELORS_DEGREE': "FCGTU|HFDVW|QJZM9|UTPWG%2COR",
    'MASTERS_DEGREE': "EXSNN|FCGTU|HFDVW|QJZM9|UTPWG%2COR",
    'DOCTORAL_DEGREE': "6QC5F%2COR"
}